= Prepare your desktop

== Prerequisit:
* Docker
* docker-compose
* erlang
* elixir
* phoenix
* postgres

== If you have question please raise an Issue on this github repository

== On Linux
=== Install asdf

If you are on linux use ASDF https://github.com/asdf-vm/asdf

=== Install Erlang

use asdf to install erlang
[source language='shell']
----
asdf plugin-add erlang
asdf install erlang 21.1
asdf global erlang 21.1
----

=== Install Elixir
[source language='shell']
----
asdf plugin-add elixir
asdf install elixir 1.7.3
asdf global elixir 1.7.3
----
=== Install Phoenix
[source language='shell']
----
mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez
----

=== Install Postgres in a container

I typically run mine with something like that : 

[source language='shell']
----
docker pull postgres:11.1

docker run -d -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 -v $HOME/tmp/docker-data/elixir_worksho/pg-data:/var/lib/postgresql/data --name postgres_elixir postgres:11.1
----

== On Windows

WARNING: Utiliser git bash (🦄) pas le cmd windows (💩)

=== Docker
download and install
https://download.docker.com/win/stable/Docker%20for%20Windows%20Installer.exe

=== Erlang
Install Erland Msi (google)https://packages.erlang-solutions.com/erlang/esl-erlang/FLAVOUR_1_general/esl-erlang_21.0~windows_amd64.exe

=== Elixir
Install elixir Msi (google)https://repo.hex.pm/elixir-websetup.exe

=== Phoenix
run :

[source language='shell']
----
mix archive.install hex phx_new 1.4.0
----

=== Postgres through Docker

No persistant data if you remove (rm) the container

[source language='shell']
----
docker pull postgres:11.1
docker run -d -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 --name postgres_elixir postgres:11.1
----

WARNING: Utiliser git bash (🦄) pas le cmd windows (💩)

== Text Editorc 

I'll present thing with VSCode +
Install those plugin : 
- vscode-elixir
- elixir snippets


== It would be awesome, and save time to everyone, if : 

[source language='shell']
----
mix new my_project
----
creates a project in myproject folder

[source language='shell']
----
mix phx.new my_phx_project
----
creates a phoenix project in myproject folder

and if postgres was running and listening on localhost
[source language='shell',subs="+quotes,+macros"]
----
psql -h localhost -U *_postgres_user_change_me_*
----
let's you connect to your database :D

== If you have question please raise an Issue on this github repository


